exclude: [Gemfile, Gemfile.lock, Rakefile, README, CNAME]
url: http://www.markwunsch.com
tumblr_url: http://blog.markwunsch.com
gems:
  - jekyll-redirect-from
sass:
  style: :compact
defaults:
  -
    scope:
      path: "tumblelog"
      # type: "posts"
    values:
      layout: "tumblelog"

