exclude: [Gemfile, Gemfile.lock, Rakefile, README, CNAME]
url: https://www.markwunsch.com
tumblr_url: https://blog.markwunsch.com
permalink: /:categories/:year/:month/:title.html
plugins:
  - jekyll-redirect-from
  - jekyll-feed
sass:
  style: :compact
defaults:
  -
    scope:
      path: "tumblelog"
    values:
      layout: "tumblelog"
  -
    scope:
      path: "tinyletter"
    values:
      layout: "tinyletter"
  -
    scope:
      path: "thinkpiece"
    values:
      layout: "thinkpiece"
